-- Seed 50 demo vessels.
-- Idempotent: only inserts when the table is empty so a re-deploy against an
-- existing volume won't duplicate data.

INSERT INTO boats (name, description, status, type, created_at)
SELECT v.name, v.description, v.status, v.type, NOW()
FROM (VALUES
  ('Adriatic Star',    'Mediterranean trading vessel with refrigerated cargo hold',            'IN_PORT',    'CARGO_SHIP'),
  ('Blue Horizon',     'Long-range ocean-going trawler with modern sonar suite',               'UNDERWAY',   'TRAWLER'),
  ('Calypso Dream',    'Luxury sailing yacht, 42 ft, carbon fibre mast',                       'IN_PORT',    'YACHT'),
  ('Dawn Breaker',     'Passenger ferry operating the coastal island route',                   'UNDERWAY',   'FERRY'),
  ('Eagle Ray',        'Sport fishing trawler with live-bait tank and fighting chair',         'MAINTENANCE','TRAWLER'),
  ('Forte dei Marmi',  'Classic wooden sailboat, restored 1970s design',                      'IN_PORT',    'SAILBOAT'),
  ('Geneva Express',   'High-speed cargo ship serving Swiss lake ports',                      'UNDERWAY',   'CARGO_SHIP'),
  ('Harbour Queen',    'Double-decker commuter ferry, 200-passenger capacity',                 'IN_PORT',    'FERRY'),
  ('Ibiza Breeze',     'Charter yacht equipped for week-long Mediterranean cruises',           'UNDERWAY',   'YACHT'),
  ('Jade Compass',     'Research trawler with onboard lab and sampling equipment',             'MAINTENANCE','TRAWLER'),
  ('Kairos',           'Racing sailboat, carbon rigging, ISAF certified',                     'IN_PORT',    'SAILBOAT'),
  ('Lagoon Pearl',     'Catamaran-style ferry serving shallow lagoon routes',                  'UNDERWAY',   'FERRY'),
  ('Mistral Wind',     'Sailing yacht with bluewater circumnavigation kit',                   'IN_PORT',    'YACHT'),
  ('Nordic Carrier',   'Ice-class cargo ship for northern Baltic operations',                  'UNDERWAY',   'CARGO_SHIP'),
  ('Ocean Nomad',      'Long-distance sailboat, single-handed crossing capable',               'IN_PORT',    'SAILBOAT'),
  ('Poseidon II',      'Deep-sea trawler with 30-tonne fish hold capacity',                   'UNDERWAY',   'TRAWLER'),
  ('Quartz Runner',    'Container cargo ship with onboard crane',                             'IN_PORT',    'CARGO_SHIP'),
  ('Riviera Sun',      'Luxury motor yacht, 58 ft, owner-operated',                           'UNDERWAY',   'YACHT'),
  ('Sea Falcon',       'Fast patrol vessel converted to private sailboat',                    'MAINTENANCE','SAILBOAT'),
  ('Thalassa',         'Roll-on roll-off ferry, vehicle deck capacity 80 cars',               'IN_PORT',    'FERRY'),
  ('Ulysses V',        'Heritage cargo schooner operating heritage freight routes',            'UNDERWAY',   'CARGO_SHIP'),
  ('Vega Light',       'Racing sailboat competing in offshore circuit events',                 'IN_PORT',    'SAILBOAT'),
  ('White Albatross',  'Expedition yacht with watermaker and solar array',                    'UNDERWAY',   'YACHT'),
  ('Xenon Tide',       'Chemical tanker with double-hull construction',                       'MAINTENANCE','CARGO_SHIP'),
  ('Yellow Fin',       'Trawler specialising in tuna and pelagic fishing',                    'IN_PORT',    'TRAWLER'),
  ('Zephyr III',       'Lightweight daysailer for club racing and leisure',                   'UNDERWAY',   'SAILBOAT'),
  ('Atlantic Rover',   'Bulk carrier transporting aggregates and minerals',                   'IN_PORT',    'CARGO_SHIP'),
  ('Bay Dancer',       'Aluminium-hulled passenger ferry, 60-seat capacity',                  'UNDERWAY',   'FERRY'),
  ('Coral Prince',     'Dive charter yacht with compressor room and dive deck',               'IN_PORT',    'YACHT'),
  ('Drifter',          'Artisanal trawler with traditional net-hauling gear',                 'MAINTENANCE','TRAWLER'),
  ('Emerald Sky',      'Sloop-rigged sailboat, family cruising configuration',                'IN_PORT',    'SAILBOAT'),
  ('Fjord Explorer',   'RoPax ferry linking mainland to island fjord settlements',            'UNDERWAY',   'FERRY'),
  ('Golden Gate',      'Feeder container cargo ship, 500 TEU capacity',                      'IN_PORT',    'CARGO_SHIP'),
  ('Helios',           'Solar-assisted sailing yacht with hybrid propulsion',                 'UNDERWAY',   'YACHT'),
  ('Ironside',         'Heavy-lift cargo vessel with retractable deck crane',                 'MAINTENANCE','CARGO_SHIP'),
  ('Jolly Mariner',    'Classic wooden ketch, charter and event hire',                        'IN_PORT',    'SAILBOAT'),
  ('Kraken Hunter',    'Commercial squid-fishing trawler with jig machines',                  'UNDERWAY',   'TRAWLER'),
  ('Lakewind',         'Inland lake ferry connecting lakeside villages',                      'IN_PORT',    'FERRY'),
  ('Moonraker',        'Sleek performance yacht, carbon keel and short rig',                  'UNDERWAY',   'YACHT'),
  ('Neptune Star',     'Stern trawler with refrigerated seawater tanks',                      'IN_PORT',    'TRAWLER'),
  ('Opaline',          'Luxury superyacht, 75 ft, stabilised for offshore comfort',           'UNDERWAY',   'YACHT'),
  ('Pacific Arrow',    'Long-haul container cargo ship with GPS tracking system',             'MAINTENANCE','CARGO_SHIP'),
  ('Quest IV',         'Ocean research sailboat operated by marine institute',                'IN_PORT',    'SAILBOAT'),
  ('Reef Runner',      'Glass-bottom tourist ferry for reef excursions',                      'UNDERWAY',   'FERRY'),
  ('Siren Song',       'Elegant sloop with teak decks and roller furling',                    'IN_PORT',    'SAILBOAT'),
  ('Triton',           'Patrol trawler with monitoring equipment for fisheries control',      'UNDERWAY',   'TRAWLER'),
  ('Umbra',            'Night-fishing trawler with high-power deck lighting',                 'MAINTENANCE','TRAWLER'),
  ('Valiant Wind',     'Ocean-racing sailboat, IMOCA 60 class',                               'IN_PORT',    'SAILBOAT'),
  ('Waverunner',       'Commuter catamaran ferry, low-wake hull design',                      'UNDERWAY',   'FERRY'),
  ('Zeal',             'Expedition cargo ship carrying scientific supplies to polar bases',   'IN_PORT',    'CARGO_SHIP')
) AS v(name, description, status, type)
WHERE NOT EXISTS (SELECT 1 FROM boats LIMIT 1);
